# Generated by Django 4.2.3 on 2023-12-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaKoVezba',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('program_vezbanja', models.IntegerField()),
            ],
        ),
    ]
